[WIP] Move to CMake targets
AliceO2Group/Common pull request #17
Opened 2018-11-01 15:29 UTC by awegrzyn

2018-11-01 17:47 UTC, awegrzyn commented
@sy-c Travis fails due to:
```
/home/travis/build/AliceO2Group/Common/test/TestSystem.cxx(65): error: in "TestGetFileSystemType": check System::getFileSystemType("/dev") == "devtmpfs" has failed
/home/travis/build/AliceO2Group/Common/test/TestSystem.cxx(66): error: in "TestGetFileSystemType": check System::getFileSystemType("/dev/shm") == "tmpfs" has failed
```
Do you think you could fix it? Otherwise I'll just disable to test.

2018-11-02 08:05 UTC, awegrzyn commented
These changes do not affect any package using `FindCommon.cmake` macro

2018-11-02 08:08 UTC, awegrzyn commented
This PR obsoletes https://github.com/AliceO2Group/Common/pull/15

2018-11-02 09:05 UTC, sy-c commented
looks good, I just need a bit of time to check a few possible extra cleanup (build_standalone and tcl)

2018-11-02 10:37 UTC, sy-c approved these changes
ok, all good for me
tried with success to rebuild infologger with this new branch

2018-11-02 10:53 UTC, Barthelemy requested changes
just minor changes

2018-11-02 10:53 UTC, Barthelemy commented on CMakeLists.txt
>  # Add compiler flags for warnings and (more importantly) fPIC and debug symbols
The comment does not make sense any more

2018-11-02 10:53 UTC, Barthelemy commented on include/Common/Version.h.in
> +#define HELLO_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
Maybe rename HELLO to COMMON ?

2018-11-02 11:03 UTC, Barthelemy approved these changes

2018-11-02 11:54 UTC, merged